name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          gh repo sync $REPOSITORY -b v0.0.x
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name 'tieum'
          git config --global user.email 'tieum@users.noreply.github.com'
          git remote add upstream https://github.com/rancher/local-path-provisioner.git
          git fetch upstream --tags
          git push origin --tags
